### ISSUE TITLE
Exclude .pyc files from sdist

### ISSUE THREAD

**Issue by jayvdb** [dephell/dephell#283] opened 2019-10-25 02:57 UTC
When doing distro packaging, comparisons of the old and new sdist tarballs is a safety measure to ensure nothing suspect has slipped in.  The .pyc files in the sdists create a lot of noise in that process.

**Comment by jayvdb** [comment] 2019-10-25 03:00
See e.g. https://build.opensuse.org/package/rdiff/home:jayvdb:py-dephell-roundtrip/python-dephell?opackage=python-dephell&oproject=devel%3Alanguages%3Apython&rev=6

**Comment by orsinium** [comment] 2019-10-25 13:03
Thank you for your report! Duplicate of #103. I also really want to see it fixed :)

**Closed by orsinium** 2019-10-25 13:03 UTC
