### ISSUE TITLE
`dephell deps convert --envs=main` includes dev dependencies (poetry.lock)

### ISSUE THREAD

**Issue by nymous** [dephell/dephell#264] opened 2019-10-09 14:18 UTC
I try to convert locked dependencies from Poetry to requirements.txt, to later build a PEX file with only the production dependencies.

When running `dephell deps convert --from=poetry.lock --to=requirements.txt --envs=main` the resulting file contains all dependencies including dev ones.

I already looked at #137 which pointed me towards the `--envs` parameter, but it doesn't seem to work how I imagined.

**Steps to reproduce:**
Using `dephell==0.7.7`

1. Initialize a Poetry project (`poetry init -n`)
2. Add prod & dev dependencies (`poetry add requests`, `poetry add -D pytest`)
3. Convert dependencies, skipping dev dependencies (`dephell deps convert --from=poetry.lock --to=requirements.txt --envs=main`)

<details>
<summary>
Expected result:
</summary>

```
certifi==2019.9.11
chardet==3.0.4
idna==2.8; python_version != "3.0.*" and python_version != "3.1.*" and python_version != "3.2.*" and python_version != "3.3.*" and python_version >= "2.7"
requests==2.22.0; python_version != "3.0.*" and python_version != "3.1.*" and python_version != "3.2.*" and python_version != "3.3.*" and python_version != "3.4.*" and python_version >= "2.7"
urllib3==1.25.6; python_version != "3.0.*" and python_version != "3.1.*" and python_version != "3.2.*" and python_version != "3.3.*" and python_version >= "2.7" and python_version < "4"
```
</details>

<details>
<summary>
Actual result:
</summary>

```
atomicwrites==1.3.0; python_version != "3.0.*" and python_version != "3.1.*" and python_version != "3.2.*" and python_version != "3.3.*" and python_version >= "2.7"
attrs==19.2.0; python_version != "3.0.*" and python_version != "3.1.*" and python_version != "3.2.*" and python_version != "3.3.*" and python_version >= "2.7"
certifi==2019.9.11
chardet==3.0.4
colorama==0.4.1; sys_platform == "win32" and python_version != "3.0.*" and python_version != "3.1.*" and python_version != "3.2.*" and python_version != "3.3.*" and python_version >= "2.7"
idna==2.8; python_version != "3.0.*" and python_version != "3.1.*" and python_version != "3.2.*" and python_version != "3.3.*" and python_version >= "2.7"
importlib-metadata==0.23; python_version < "3.8" and python_version >= "2.7" and python_version != "3.0" and python_version != "3.1" and python_version != "3.2" and python_version != "3.3"
more-itertools==7.2.0; python_version >= "3.4"
packaging==19.2; python_version != "3.0.*" and python_version != "3.1.*" and python_version != "3.2.*" and python_version != "3.3.*" and python_version >= "2.7"
pluggy==0.13.0; python_version != "3.0.*" and python_version != "3.1.*" and python_version != "3.2.*" and python_version != "3.3.*" and python_version >= "2.7"
py==1.8.0; python_version != "3.0.*" and python_version != "3.1.*" and python_version != "3.2.*" and python_version != "3.3.*" and python_version >= "2.7"
pyparsing==2.4.2; python_version != "3.0.*" and python_version != "3.1.*" and python_version != "3.2.*" and python_version >= "2.6"
pytest==5.2.1; python_version >= "3.5"
requests==2.22.0; python_version != "3.0.*" and python_version != "3.1.*" and python_version != "3.2.*" and python_version != "3.3.*" and python_version != "3.4.*" and python_version >= "2.7"
six==1.12.0; python_version != "3.0.*" and python_version != "3.1.*" and python_version >= "2.6"
urllib3==1.25.6; python_version != "3.0.*" and python_version != "3.1.*" and python_version != "3.2.*" and python_version != "3.3.*" and python_version >= "2.7" and python_version < "4"
wcwidth==0.1.7
zipp==0.6.0; python_version < "3.8" and python_version >= "2.7"
```
</details>

**Comment by orsinium** [comment] 2019-10-25 12:22
Hmm, can't reproduce.

`pyproject.toml`:

```toml
[tool.poetry]
name = "tmp"
version = "0.1.0"
description = ""
authors = ["Gram <master_fess@mail.ru>"]

[tool.poetry.dependencies]
python = "^3.6"
requests = "*"

[tool.poetry.dev-dependencies]
pytest = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

Resulting `requirements.txt`:

```
certifi==2019.9.11
chardet==3.0.4
idna==2.8; python_version != "3.0.*" and python_version != "3.1.*" and python_version != "3.2.*" and python_version != "3.3.*" and python_version >= "2.7"
requests==2.22.0; python_version != "3.0.*" and python_version != "3.1.*" and python_version != "3.2.*" and python_version != "3.3.*" and python_version != "3.4.*" and python_version >= "2.7"
urllib3==1.25.6; python_version != "3.0.*" and python_version != "3.1.*" and python_version != "3.2.*" and python_version != "3.3.*" and python_version >= "2.7" and python_version < "4"
```

Possible causes of differences:

1. I'm using DepHell 0.7.8, and this bug was fixed in the latest release.
1. Your `pyproject.toml` is different.

Could you check it again on the latest version and provide generated `pyproject.toml`, please?

**Comment by nymous** [comment] 2019-10-25 14:13
I retried with dephell 0.7.8 installed through the recommended method (`curl | python`).

My `pyproject.toml`:
```toml
[tool.poetry]
name = "tmp.nxehdzkkmi"
version = "0.1.0"
description = ""
authors = ["Thomas Gaudin <email@domain.tld>"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.22"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

When I run `dephell deps convert --from=poetry.lock --to=requirements.txt --envs=main`, `requirements.txt`:
```
atomicwrites==1.3.0; python_version != "3.0.*" and python_version != "3.1.*" and python_version != "3.2.*" and python_version != "3.3.*" and python_version >= "2.7"
attrs==19.3.0; python_version != "3.0.*" and python_version != "3.1.*" and python_version != "3.2.*" and python_version != "3.3.*" and python_version >= "2.7"
certifi==2019.9.11
chardet==3.0.4
colorama==0.4.1; sys_platform == "win32" and python_version != "3.0.*" and python_version != "3.1.*" and python_version != "3.2.*" and python_version != "3.3.*" and python_version >= "2.7"
idna==2.8; python_version != "3.0.*" and python_version != "3.1.*" and python_version != "3.2.*" and python_version != "3.3.*" and python_version >= "2.7"
importlib-metadata==0.23; python_version < "3.8" and python_version >= "2.7" and python_version != "3.0" and python_version != "3.1" and python_version != "3.2" and python_version != "3.3"
more-itertools==7.2.0; python_version >= "3.4"
packaging==19.2; python_version != "3.0.*" and python_version != "3.1.*" and python_version != "3.2.*" and python_version != "3.3.*" and python_version >= "2.7"
pluggy==0.13.0; python_version != "3.0.*" and python_version != "3.1.*" and python_version != "3.2.*" and python_version != "3.3.*" and python_version >= "2.7"
py==1.8.0; python_version != "3.0.*" and python_version != "3.1.*" and python_version != "3.2.*" and python_version != "3.3.*" and python_version >= "2.7"
pyparsing==2.4.2; python_version != "3.0.*" and python_version != "3.1.*" and python_version != "3.2.*" and python_version >= "2.6"
pytest==5.2.2; python_version >= "3.5"
requests==2.22.0; python_version != "3.0.*" and python_version != "3.1.*" and python_version != "3.2.*" and python_version != "3.3.*" and python_version != "3.4.*" and python_version >= "2.7"
six==1.12.0; python_version != "3.0.*" and python_version != "3.1.*" and python_version >= "2.6"
urllib3==1.25.6; python_version != "3.0.*" and python_version != "3.1.*" and python_version != "3.2.*" and python_version != "3.3.*" and python_version >= "2.7" and python_version < "4"
wcwidth==0.1.7
zipp==0.6.0; python_version < "3.8" and python_version >= "2.7"
```

When I run `dephell deps convert --from=pyproject.toml --to=requirements.txt --envs=main`, `requirements.txt`:
```
pytest==5.*,>=5.2.0
requests==2.*,>=2.22.0
```

When I run `dephell deps convert --from=pyproject.toml --to=requirements.lock --envs=main`, `requirements.lock`:
```
configparser==4.0.2; python_version < "3" \
  --hash sha256:254c1d9c79f60c45dfde850850883d5aaa7f19a23f13561243a050d5a7c3fe4c \
  --hash sha256:c7d282687a5308319bf3d2e7706e575c635b0a470342641c93bea0ea3b5331df \
  # ^ from importlib-metadata
contextlib2==0.6.0.post1; python_version < "3" \
  --hash sha256:01f490098c18b19d2bd5bb5dc445b2054d2fa97f09a4280ba2c5f3c394c8162e \
  --hash sha256:3355078a159fbb44ee60ea80abd0d87b80b78c248643b49aa6d94673b413609b \
  # ^ from importlib-metadata
pyparsing==2.4.2 \
  --hash sha256:6f98a7b9397e206d78cc01df10131398f1c8b8510a2f4d97d9abd82e1aacdd80 \
  --hash sha256:d9338df12903bbf5d65a0e4e87c2161968b10d2e489652bb47001d82a9b028b4 \
  # ^ from packaging
scandir==1.10.0; python_version < "3.5" \
  --hash sha256:2586c94e907d99617887daed6c1d102b5ca28f1085f90446554abf1faf73123e \
  --hash sha256:2ae41f43797ca0c11591c0c35f2f5875fa99f8797cb1a1fd440497ec0ae4b022 \
  --hash sha256:2b8e3888b11abb2217a32af0766bc06b65cc4a928d8727828ee68af5a967fa6f \
  --hash sha256:2c712840c2e2ee8dfaf36034080108d30060d759c7b73a01a52251cc8989f11f \
  --hash sha256:4d4631f6062e658e9007ab3149a9b914f3548cb38bfb021c64f39a025ce578ae \
  --hash sha256:67f15b6f83e6507fdc6fca22fedf6ef8b334b399ca27c6b568cbfaa82a364173 \
  --hash sha256:7d2d7a06a252764061a020407b997dd036f7bd6a175a5ba2b345f0a357f0b3f4 \
  --hash sha256:8c5922863e44ffc00c5c693190648daa6d15e7c1207ed02d6f46a8dcc2869d32 \
  --hash sha256:92c85ac42f41ffdc35b6da57ed991575bdbe69db895507af88b9f499b701c188 \
  --hash sha256:b24086f2375c4a094a6b51e78b4cf7ca16c721dcee2eddd7aa6494b42d6d519d \
  --hash sha256:cb925555f43060a1745d0a321cca94bcea927c50114b623d73179189a4e100ac \
  # ^ from pathlib2
six==1.12.0 \
  --hash sha256:3350809f0555b11f552448330d0b52d5f24c91a322ea4a15ef22629740f3761c \
  --hash sha256:d16a0141ec1a18405cd4ce8b4613101da75da0e9a7aec5bdd4fa804d0e0eba73 \
  # ^ from packaging, pathlib2
zipp==0.6.0 \
  --hash sha256:3718b1cbcd963c7d4c5511a8240812904164b7f381b647143a89d3b98f9bcd8e \
  --hash sha256:f06903e9f1f43b12d371004b4ac7b06ab39a44adc747266928ae6debfa7b3335 \
  # ^ from importlib-metadata
atomicwrites==1.3.0 \
  --hash sha256:03472c30eb2c5d1ba9227e4c2ca66ab8287fbfbbda3888aa93dc2e28fc6811b4 \
  --hash sha256:75a9445bac02d8d058d5e1fe689654ba5a6556a1dfd8ce6ec55a0ed79866cfa6 \
  # ^ from pytest
attrs==19.3.0 \
  --hash sha256:08a96c641c3a74e44eb59afb61a24f2cb9f4d7188748e76ba4bb5edfa3cb7d1c \
  --hash sha256:f7b7ce16570fe9965acd6d30101a28f62fb4a7f9e926b3bbc9b61f8b04247e72 \
  # ^ from pytest
certifi==2019.9.11 \
  --hash sha256:e4f3620cfea4f83eedc95b24abd9cd56f3c4b146dd0177e83a21b4eb49e21e50 \
  --hash sha256:fd7c7c74727ddcf00e9acd26bba8da604ffec95bf1c2144e67aff7a8b50e6cef \
  # ^ from requests
chardet==3.0.4 \
  --hash sha256:84ab92ed1c4d4f16916e05906b6b75a6c0fb5db821cc65e70cbd64a3e2a5eaae \
  --hash sha256:fc323ffcaeaed0e0a02bf4d117757b98aed530d9ed4531e3e15460124c106691 \
  # ^ from requests
colorama==0.4.1; sys_platform == "win32" \
  --hash sha256:05eed71e2e327246ad6b38c540c4a3117230b19679b875190486ddd2d721422d \
  --hash sha256:f8ac84de7840f5b9c4e3347b3c1eaa50f7e49c2b07596221daec5edaabbd7c48 \
  # ^ from pytest
idna==2.8 \
  --hash sha256:c357b3f628cf53ae2c4c05627ecc484553142ca23264e593d327bcde5e9c3407 \
  --hash sha256:ea8b7f6188e6fa117537c3df7da9fc686d485087abf6ac197f9c46432f7e4a3c \
  # ^ from requests
importlib-metadata==0.23; python_version < "3.8" or python_version < "3.8" \
  --hash sha256:aa18d7378b00b40847790e7c27e11673d7fed219354109d0e7b9e5b25dc3ad26 \
  --hash sha256:d5f18a79777f3aa179c145737780282e27b508fc8fd688cb17c7a813e8bd39af \
  # ^ from pluggy, pytest
more-itertools==7.2.0 \
  --hash sha256:409cd48d4db7052af495b09dec721011634af3753ae1ef92d2b32f73a745f832 \
  --hash sha256:92b8c4b06dac4f0611c0729b2f2ede52b2e1bac1ab48f089c7ddc12e26bb60c4 \
  # ^ from pytest, zipp
packaging==19.2 \
  --hash sha256:28b924174df7a2fa32c1953825ff29c61e2f5e082343165438812f00d3a7fc47 \
  --hash sha256:d9551545c6d761f3def1677baf08ab2a3ca17c56879e70fecba2fc4dde4ed108 \
  # ^ from pytest
pathlib2==2.3.5; python_version < "3.6" or python_version == "3.4.*" or python_version < "3" \
  --hash sha256:0ec8205a157c80d7acc301c0b18fbd5d44fe655968f5d947b6ecef5290fc35db \
  --hash sha256:6cd9a47b597b37cc57de1c05e56fb1a1c9cc9fab04fe78c29acd090418529868 \
  # ^ from importlib-metadata, pytest
pluggy==0.13.0 \
  --hash sha256:0db4b7601aae1d35b4a033282da476845aa19185c1e6964b25cf324b5e4ec3e6 \
  --hash sha256:fa5fa1622fa6dd5c030e9cad086fa19ef6a0cf6d7a2d12318e10cb49d6d68f34 \
  # ^ from pytest
py==1.8.0 \
  --hash sha256:64f65755aee5b381cea27766a3a147c3f15b9b6b9ac88676de66ba2ae36793fa \
  --hash sha256:dc639b046a6e2cff5bbe40194ad65936d6ba360b52b3c3fe1d08a82dd50b5e53 \
  # ^ from pytest
urllib3==1.25.6 \
  --hash sha256:3de946ffbed6e6746608990594d08faac602528ac7015ac28d33cee6a45b7398 \
  --hash sha256:9a107b99a5393caf59c7aa3c1249c16e6879447533d0887f4336dde834c7be86 \
  # ^ from requests
wcwidth==0.1.7 \
  --hash sha256:3df37372226d6e63e1b1e1eda15c594bca98a22d33a23832a90998faa96bc65e \
  --hash sha256:f4ebe71925af7b40a864553f761ed559b43544f8f71746c2d756c7fe788ade7c \
  # ^ from pytest
pytest==5.2.2 \
  --hash sha256:27abc3fef618a01bebb1f0d6d303d2816a99aa87a5968ebc32fe971be91eb1e6 \
  --hash sha256:58cee9e09242937e136dbb3dab466116ba20d6b7828c7620f23947f37eb4dae4 \
  # ^ from tmp-nxehdzkkmi
requests==2.22.0 \
  --hash sha256:11e007a8a2aa0323f5a921e9e6a2d7e4e67d9877e85773fba9ba6419025cbeb4 \
  --hash sha256:9cf5292fcd0f598c671cfc1e0d7d1a7f13bb8085e9a590f48c010551dc6c4b31 \
  # ^ from tmp-nxehdzkkmi
```

When I run `dephell deps convert --from=poetry.lock --to=requirements.lock --envs=main`, I get an error (which is probably another issue):
```
WARNING conflict was found
Incompatible python constraint for zipp.

Required by marker: <3.8,>=2.7.

Supported:
 + Version 0.6.0 compatible with python >=2.7.
 + Version 0.5.2 compatible with python >=2.7.
 + Version 0.5.1 compatible with python >=2.7.
 + Version 0.5.0 compatible with python >=2.7.
 + Version 0.4.0 compatible with python >=2.7.
 + Version 0.3.3 compatible with python >=2.7.
 + Version 0.3.2 compatible with python >=2.7.
 + Version 0.3.1 compatible with python >=2.7.
 + Version 0.3.0 compatible with python >=2.7.
 + Version 0.2.1 compatible with python >=2.7.
 + Version 0.2.0 compatible with python >=2.7.
 + Version 0.1.0 compatible with python >=2.7.
```

More information about my environment:
- Python 3.7.4
- ArchLinux

**Comment by orsinium** [comment] 2019-10-25 14:22
Oh, I see, it's from lockfile. Thank you!

**Closed** 2019-11-19 09:46 UTC
Labels: bug
