### ISSUE TITLE
Forbid to use package look-a-likes

### ISSUE THREAD

**Issue by sobolevn** [dephell/dephell#315] opened 2019-11-29 09:37 UTC
Hi! 

I have an idea I want to share. 
Sometimes people install packages that have similar names to popular ones:
- `request`
- `attr`
- `django-rest-framework` and `rest_framework`

So, maybe it is a good idea to warn users about it.

**Comment by orsinium** [comment] 2019-11-29 13:00
Duplicate of #133. First of all, I'm going to make a command for it and then re-use it in other commands. We already have mapping from pipreqs, btw, it used in `imports` reader. 

Contributions are welcome :)

**Closed by orsinium** 2019-11-29 13:00 UTC

**Comment by sobolevn** [comment] 2019-11-29 17:18
Awesome! 👍
